trigger:
  branches:
    include:
      - main

variables:
  imageRepositoryBackend: "feedback-board-backend"
  containerRegistry: "bodatero.azurecr.io"
  dockerRegistryServiceConnection: "bodatero ACR connection"
  NODE_VERSION: "20.11.0"

pool:
  name: "Default"

stages:
  - stage: Build
    jobs:
      - job: Build_Backend
        displayName: Build and Push Backend
        steps:
          - checkout: self

          - task: Docker@2
            displayName: Build and Push Backend Image
            inputs:
              command: buildAndPush
              repository: $(imageRepositoryBackend)
              dockerfile: backend/Dockerfile
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: latest

      - job: Build_And_Deploy_Frontend
        displayName: Build and Deploy Frontend
        steps:
          - checkout: self

          - task: UseNode@1
            inputs:
              version: "20.x"

          - script: |
              cd frontend
              npm ci
            displayName: Install dependencies

          - script: |
              cd frontend
              npm run build
            displayName: Build SolidJS app

          - script: |
              node -v
              npm -v
            displayName: "Check Node version"

          - task: AzureStaticWebApp@0
            displayName: Deploy to Azure Static Web Apps
            inputs:
              version: $(NODE_VERSION)
              app_location: "frontend"
              output_location: "frontend/dist"
              azure_static_web_apps_api_token: "$(deployment_token)"
