trigger:
  branches:
    include:
      - main

variables:
  imageRepositoryBackend: "feedback-board-backend"
  containerRegistry: "bodatero.azurecr.io"
  dockerRegistryServiceConnection: "bodatero ACR connection"
  API_URL: ""

pool:
  name: "Default"

stages:
  - stage: Build
    jobs:
      - job: Build_Backend
        displayName: Build and Push Backend
        steps:
          - checkout: self

          - task: Docker@2
            displayName: Build and Push Backend Image
            inputs:
              command: buildAndPush
              repository: $(imageRepositoryBackend)
              dockerfile: backend/Dockerfile
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: latest

      - job: Build_And_Deploy_Frontend
        displayName: Build and Deploy Frontend
        steps:
          - checkout: self

          - task: UseNode@1
            inputs:
              version: "20.x"

          - script: |
              cd frontend
              npm ci
            displayName: Install dependencies

          - script: |
              cd frontend
              npm run build
            displayName: Build SolidJS app
            env:
              VITE_API_URL: "$(API_URL)"

          - task: AzureStaticWebApp@0
            displayName: Deploy to Azure Static Web Apps
            inputs:
              app_location: "frontend/dist"
              azure_static_web_apps_api_token: "$(deployment_token)"
              skip_app_build: true

  - stage: Deploy_Backend
    displayName: Deploy Backend to ACA
    dependsOn: Build
    jobs:
      - job: Deploy_Backend_Job
        displayName: Deploy Backend
        steps:
          - task: AzureWebAppContainer@1
            inputs:
              appName: "feedback-board-backend"
              azureSubscription: "test-group connection"
              deployToSlotOrASE: true
              resourceGroupName: "test-group"
              slotName: "production"
              configurationStrings: "-WEBSITES_PORT 3001"
              containers: "bodatero.azurecr.io/feedback-board-backend:latest"
